from django.db import models
from django.utils import timezone

class Syslog(models.Model):
    type = models.CharField(max_length=50, default="")  # Log type/heading (i.e Appointment Created, EMR viewing)
    message = models.CharField(max_length=200, default="")  # Log message, usually generated by the system
    date_created = models.DateTimeField(default=timezone.now)

    @staticmethod
    def log(_type, _message):
        Syslog.objects.create(type=_type, message = _message, date_created = timezone.now())

    @staticmethod
    def logUser(_type, _message, _user):
        _message += ":{0}, {1}".format(_user.lastName, _user.firstName)
        Syslog.log(_type, _message)

    @staticmethod
    def unauth_acess(request):
        Syslog.objects.create(type="Delete", message="Attemted unauthorized access at url: {0} by user {1}".format(request.path, request.user.username))

    @staticmethod
    def deleteEvent(event, user):
        Syslog.objects.create(type="Delete", message = "User: {0} deleted event: {1}".format(user.user.get_full_name(), event.description))

    @staticmethod
    def modifyEvent(event, user):
        Syslog.objects.create(type = "Modify", message = "User: {0} modified event: {1} with primary key: {2}".format(user.user.get_full_name(), event.description, event.id))

    @staticmethod
    def viewEMR(emr, user):
        Syslog.objects.create(type="View", message="User: {0} viewed emr log with primary key {1}".format(user.user.get_full_name(), emr.id))

    @staticmethod
    def createEvent(event, user):
        Syslog.objects.create(type="Create", message="User: {0} created event with description: {1} and primary key {2}".format(user.user.get_full_name(), event.description, event.id))

    @staticmethod
    def userLogin(user):
        Syslog.objects.create(type="Login",
                              message="User: {0} created event with pk: {1}".format(
                                  user.get_full_name(), user.id))
    @staticmethod
    def userCreate(user):
        Syslog.objects.create(type="Create",
                              message="User: {0} registered, pk: {1}".format(
                                  user.user.username, user.id))
    @staticmethod
    def editProfile(user):
        Syslog.objects.create(type="Edit",
                              message="User: {0} edited their profile, pk: {1}".format(
                                  user.user.get_full_name(), user.id))