# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-28 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EMRNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(default='', max_length=500)),
                ('emr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.EMR')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EMRTrackedMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(default='', max_length=200)),
                ('comments', models.CharField(default='', max_length=500)),
                ('emr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.EMR')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EMRVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('restingBPM', models.IntegerField(default=0)),
                ('bloodPressure', models.CharField(default='', max_length=10)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('comments', models.CharField(default='', max_length=1000)),
                ('emr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.EMR')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
