from django.shortcuts import render
from user.models import *
from django.contrib import messages
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.contrib.auth.models import User
from emr.models import EMR
from hospital.models import *
from syslogging.models import *


#todo see if needed

# from User.models import *
# from .forms import PatientForm

# Create your views here.

class Register(View):

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],  # cleaned_data is autogenerated data. can be modified in form
                password=form.cleaned_data['password1'],
            )

            e = EMR.objects.create()
            p = Patient.objects.create(user=user, emr = e, insuranceNum=form.cleaned_data['insuranceNum'], hospital=form.cleaned_data['hospital'])
            p.save()

            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, user)

            if hasattr(user, 'patient'):
                request.session['user_type'] = 'patient'
            elif hasattr(user, 'nurse'):
                request.session['user_type'] = 'nurse'
            elif hasattr(user, 'doctor'):
                request.session['user_type'] = 'doctor'
            Syslog.userCreate(p)
            return HttpResponseRedirect(reverse('user:eProfile'))
        return HttpResponseRedirect(reverse('login'))

    def get(self, request):
        form = RegistrationForm()
        variables = RequestContext(request, {'form': form})
        return render(request, 'registration/register.html', variables)

class LoginView(View):

    def post(self, request):
        lform = LoginForm(request.POST)

        if(lform.is_valid()):
            user = authenticate(username=lform.cleaned_data['username'], password=lform.cleaned_data['password'])
            if user is not None:
                login(request, user)
                Syslog.userLogin(user)
                return HttpResponseRedirect(reverse('user:dashboard'))

        return HttpResponseRedirect(reverse('login'))

    def get(self, request):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('user:dashboard'))

        form = LoginForm()

        return render(request, 'logIn/index.html', {'form': form})


def register_success(request):
    return render_to_response('registration/success.html')

def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))


@login_required
def home(request):
    return render_to_response('home.html',{'user': request.user })


